import { useMemo } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useAgentStore } from "@/lib/agent-store";
import { AgentTestPane } from "@/components/agent-test-pane";
import { Copy, Download, Code2, FileJson, Sparkles, Play, Wrench, Palette, Search, Image, Calculator, Globe, FileText, Mail, MessageSquare, Database, Lock, Zap } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export function CodePreview() {
  const { builderState } = useAgentStore();
  const { toast } = useToast();
  const currentAgent = builderState.currentAgent;

  const jsonConfig = useMemo(() => {
    if (!currentAgent) {
      return JSON.stringify(
        {
          name: "AI Assistant",
          goal: "Help users with various tasks",
          tools: [],
          model: "gpt-4o",
          temperature: 0.7,
        },
        null,
        2
      );
    }

    return JSON.stringify(
      {
        name: currentAgent.name || "AI Assistant",
        goal: currentAgent.goal || "",
        personality: currentAgent.personality || "",
        tools: currentAgent.tools || [],
        model: currentAgent.modelId || "gpt-4o",
        temperature: currentAgent.temperature || 0.7,
        maxTokens: currentAgent.maxTokens || 4096,
      },
      null,
      2
    );
  }, [currentAgent]);

  const pythonCode = useMemo(() => {
    const agentName = currentAgent?.name?.replace(/\s+/g, "") || "AIAssistant";
    const tools = currentAgent?.tools || [];
    const modelId = currentAgent?.modelId || "gpt-4o";

    return `"""
${currentAgent?.name || "AI Assistant"} - Generated by AgentForge
${currentAgent?.goal ? `Goal: ${currentAgent.goal}` : ""}
"""

from langchain.agents import AgentExecutor, create_openai_functions_agent
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.tools import Tool
import os

# Initialize the model
llm = ChatOpenAI(
    model="${modelId}",
    temperature=${currentAgent?.temperature || 0.7},
    max_tokens=${currentAgent?.maxTokens || 4096}
)

# Define system prompt
system_prompt = """${currentAgent?.personality || "You are a helpful AI assistant."}

Your primary goal: ${currentAgent?.goal || "Help users with their tasks."}

Be thorough, accurate, and helpful in all your responses.
"""

# Create prompt template
prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

# Define tools
tools = [
${tools
  .map(
    (tool) => `    Tool(
        name="${tool}",
        description="Tool for ${tool.replace(/_/g, " ")}",
        func=lambda x: f"[${tool}] Executed with: {x}"
    ),`
  )
  .join("\n")}
]

# Create agent
agent = create_openai_functions_agent(llm, tools, prompt)
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    handle_parsing_errors=True
)

# Run the agent
if __name__ == "__main__":
    while True:
        user_input = input("You: ")
        if user_input.lower() in ["exit", "quit"]:
            break
        response = agent_executor.invoke({"input": user_input, "chat_history": []})
        print(f"Agent: {response['output']}")
`;
  }, [currentAgent]);

  // Tool icons mapping
  const getToolIcon = (tool: string) => {
    const toolLower = tool.toLowerCase();
    if (toolLower.includes("search") || toolLower.includes("web")) return Globe;
    if (toolLower.includes("image") || toolLower.includes("vision")) return Image;
    if (toolLower.includes("code") || toolLower.includes("python")) return Code2;
    if (toolLower.includes("math") || toolLower.includes("calc")) return Calculator;
    if (toolLower.includes("file") || toolLower.includes("document")) return FileText;
    if (toolLower.includes("email") || toolLower.includes("mail")) return Mail;
    if (toolLower.includes("chat") || toolLower.includes("message")) return MessageSquare;
    if (toolLower.includes("database") || toolLower.includes("sql")) return Database;
    if (toolLower.includes("api") || toolLower.includes("fetch")) return Zap;
    return Wrench;
  };

  const handleCopy = async (content: string, type: string) => {
    await navigator.clipboard.writeText(content);
    toast({
      title: "Copied!",
      description: `${type} copied to clipboard`,
    });
  };

  const handleDownload = (content: string, filename: string) => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded!",
      description: `${filename} saved`,
    });
  };

  return (
    <div className="flex flex-col h-full">
      <div className="flex items-center justify-between p-4 border-b">
        <div className="flex items-center gap-2">
          <Code2 className="w-4 h-4 text-muted-foreground" />
          <span className="font-medium text-sm">Code Preview</span>
          {builderState.step === "complete" && (
            <Badge variant="secondary" className="text-xs">
              <Sparkles className="w-3 h-3 mr-1" />
              Ready
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => handleCopy(pythonCode, "Python code")}
            data-testid="button-copy-code"
          >
            <Copy className="w-3 h-3 mr-1" />
            Copy
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => handleDownload(pythonCode, "agent.py")}
            data-testid="button-download-code"
          >
            <Download className="w-3 h-3 mr-1" />
            Export
          </Button>
        </div>
      </div>

      <Tabs defaultValue="json" className="flex-1 flex flex-col">
        <div className="border-b px-4">
          <TabsList className="h-10">
            <TabsTrigger value="json" className="text-xs" data-testid="tab-json">
              <FileJson className="w-3 h-3 mr-1" />
              Config
            </TabsTrigger>
            <TabsTrigger value="python" className="text-xs" data-testid="tab-python">
              <Code2 className="w-3 h-3 mr-1" />
              Python
            </TabsTrigger>
            <TabsTrigger value="test" className="text-xs" data-testid="tab-test">
              <Play className="w-3 h-3 mr-1" />
              Test
            </TabsTrigger>
            <TabsTrigger value="details" className="text-xs" data-testid="tab-details">
              <Palette className="w-3 h-3 mr-1" />
              Details
            </TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value="json" className="flex-1 m-0 data-[state=inactive]:hidden">
          <ScrollArea className="h-full">
            <pre className="p-4 text-xs font-mono text-muted-foreground overflow-x-auto">
              <code data-testid="code-json">{jsonConfig}</code>
            </pre>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="python" className="flex-1 m-0 data-[state=inactive]:hidden">
          <ScrollArea className="h-full">
            <pre className="p-4 text-xs font-mono text-muted-foreground overflow-x-auto">
              <code data-testid="code-python">{pythonCode}</code>
            </pre>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="test" className="flex-1 m-0 data-[state=inactive]:hidden overflow-hidden">
          <AgentTestPane />
        </TabsContent>

        <TabsContent value="details" className="flex-1 m-0 data-[state=inactive]:hidden overflow-hidden">
          <ScrollArea className="h-full">
            <div className="p-4 space-y-6">
              {/* Personality Section */}
              <div>
                <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
                  <Palette className="w-4 h-4 text-primary" />
                  Personality
                </h3>
                <div className="bg-muted/50 rounded-lg p-4">
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {currentAgent?.personality || "No personality defined yet. Chat with the builder to set one!"}
                  </p>
                </div>
              </div>

              {/* Tools Section */}
              <div>
                <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
                  <Wrench className="w-4 h-4 text-primary" />
                  Tools & Capabilities
                </h3>
                {currentAgent?.tools && currentAgent.tools.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {currentAgent.tools.map((tool) => {
                      const ToolIcon = getToolIcon(tool);
                      return (
                        <Badge
                          key={tool}
                          variant="secondary"
                          className="px-3 py-1.5 text-xs flex items-center gap-1.5"
                        >
                          <ToolIcon className="w-3.5 h-3.5" />
                          {tool.replace(/_/g, " ")}
                        </Badge>
                      );
                    })}
                  </div>
                ) : (
                  <p className="text-sm text-muted-foreground">
                    No tools added yet. Tools give your agent special abilities!
                  </p>
                )}
              </div>

              {/* Model Info */}
              <div>
                <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
                  <Zap className="w-4 h-4 text-primary" />
                  Model Settings
                </h3>
                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-muted/50 rounded-lg p-3">
                    <p className="text-xs text-muted-foreground">Model</p>
                    <p className="text-sm font-medium mt-1">{currentAgent?.modelId || "Not selected"}</p>
                  </div>
                  <div className="bg-muted/50 rounded-lg p-3">
                    <p className="text-xs text-muted-foreground">Temperature</p>
                    <p className="text-sm font-medium mt-1">{currentAgent?.temperature || 0.7}</p>
                  </div>
                </div>
              </div>

              {/* Goal */}
              {currentAgent?.goal && (
                <div>
                  <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-primary" />
                    Goal
                  </h3>
                  <div className="bg-primary/5 border border-primary/20 rounded-lg p-4">
                    <p className="text-sm">{currentAgent.goal}</p>
                  </div>
                </div>
              )}
            </div>
          </ScrollArea>
        </TabsContent>
      </Tabs>
    </div>
  );
}
